export const GET_LANDING_DATA = 'GET_LANDING_DATA';
export const GET_INTERVIEW_DATA = 'GET_INTERVIEW_DATA';
export const GET_INTERVIEW_DATA_ERROR = 'GET_INTERVIEW_DATA_ERROR';
export const GET_PAGE_TRANSITION_DATA = 'GET_PAGE_TRANSITION_DATA';
export const SET_POLICY_NUMBER = 'SET_POLICY_NUMBER';